language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - "node_modules"
install:
  - npm ci
script:
  - npm run test:coverage
  - npm run build
  - npm run build:prod
  - npm run lint:ci
  - npm run lint:styles
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
deploy:
  provider: script
  script: npm run storybook:deploy -- --ci
  skip-cleanup: true
  on:
    tags: true
