version: 2

default: &defaults
  working_directory: ~/oneui
  docker:
    - image: circleci/node:lts

jobs:
  install: # Install and cache project dependencies
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: oneui-npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: oneui-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test: # Run tests, build bundle and lint code
    <<: *defaults
    environment:
      COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
    steps:
      - attach_workspace:
          at: ~/oneui
      - run: npm test:coverage
      - run: npm run build
      - run: npm run build:prod
      - run: npm run lint:ci
      - run: npm run lint:styles
      - run: npm run coveralls

  deploy: # Deploy Storybook to Github Pages
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/oneui
      - run:
          name: Deploy Storybook
          command: npm run storybook:deploy -- --ci

workflows:
  version: 2
  deploy-on-git-tag: # Run deploy job on git tag
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
