version: 2.1

orbs: # load coveralls package
  coveralls: coveralls/coveralls@1.0.6

defaults: &defaults
  working_directory: ~/oneui
  docker:
    - image: circleci/node:lts

workspace: &workspace
  - attach_workspace:
      at: ~/oneui

jobs:
  install: # Install and cache project dependencies
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: oneui-npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: oneui-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test: # Run tests, build bundle and lint code
    <<: *defaults
    steps:
      <<: *workspace
      - run: npm run test:coverage -- -w 1 # set max workers to 1
      - coveralls/upload

  build:
    <<: *defaults
    steps:
      <<: *workspace
      - run: npm run build:prod

  lint:
    <<: *defaults
    steps:
      <<: *workspace
      - run: npm run lint:ci
      - run: npm run lint:styles

  deploy: # Deploy Storybook to Github Pages
    <<: *defaults
    steps:
      <<: *workspace
      - run:
          name: Deploy Storybook
          command: npm run storybook:deploy -- --ci

workflows:
  deploy-on-git-tag: # Run deploy job on git tag
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
